#!/bin/sh

alias nvimrc="nvim ~/.config/nvim/"

alias allow_net="sudo systemctl start NetworkManager"
alias update="sudo pacman -Syu && paru -Syu"

# File path shortcuts
alias fun="cd ~/projects/fun"
alias work="cd ~/projects/work"
alias school="cd ~/projects/school"
alias contrib="cd ~/projects/contributions"
alias contribute="cd ~/projects/contributions"

# Personal shortcuts
alias reconfig="bash $HOME/.hick-os/scripts/link-configs.sh"
alias config="nvim $HOME/.hick-os/.config"
alias hick="cd $HOME/.hick-os"

# Server connection aliases
# These are local ip"s so it"s fine to push to public
alias web_host="ssh -i ~/.ssh/hickey-server -p 2222 hickstoor@10.159.158.57"
alias git_host="ssh -i ~/.ssh/hickey-server -p 2222 git@10.159.158.57"
alias data_host="ssh -i ~/.ssh/hickey-server hickstoor@10.159.158.69"
function remote_ip() {
  # SECRET: DO NOT COMMIT with ip
  echo "{MY_REMOTE_IP}"
}

alias zsh-update-plugins='find "$ZDOTDIR/plugins" -type d -exec test -e "{}/.git" ";" -print0 | xargs -I {} -0 git -C {} pull -q'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias ripgrep="rg --color=auto"

# Confirm before overwriting something
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# Modern replacements for specific tools
alias ls="eza"
alias cat="bat"
alias yay="paru"

# easier to read disk
alias df="df -h"     # human-readable sizes
alias free="free -m" # show sizes in MB

# get top process eating memory
alias psmem="ps auxf | sort -nr -k 4 | head -5"

# get top process eating cpu ##
alias pscpu="ps auxf | sort -nr -k 3 | head -5"

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

alias mach_java_mode="export SDKMAN_DIR="$HOME/.sdkman" && [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh""

alias m="git checkout master"
alias s="git checkout stable"
