# Disable random quotes over my wallpaper bc
# who the hell thought this was a sane default?
splash = false

# Main (center) monitor
wallpaper {
  monitor = DP-2
  path = ~/.hick-os/wallpapers/painting-alexander-the-great-visiting-achilles-tomb.jpg
  fit_mode = cover
}

# Left Monitor
wallpaper {
  monitor = HDMI-A-1
  path = ~/.hick-os/wallpapers/spiral-galaxy-portrait.jpg
  fit_mode = cover
}

# Right Monitor
#
# NOTE: This is also my drawing tablet when in use.
wallpaper {
  monitor = HDMI-A-2
  path = ~/.hick-os/wallpapers/spiral-galaxy-portrait.jpg
  fit_mode = cover
}

# Fallback
wallpaper {
  monitor =
  path = ~/.hick-os/wallpapers/spiral-galaxy-portrait.jpg
  fit_mode = cover
}
