# Source all the separated hyprland config files.
source = ~/.config/hypr/init.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/styling.conf
source = ~/.config/hypr/options.conf
source = ~/.config/hypr/wr_alacritty.conf
source = ~/.config/hypr/workspaces.conf
source = ~/.config/hypr/window_rules.conf
