# Hyprland keybinding config.
#
# NOTE: Docs @ https://wiki.hyprland.org/Configuring/Binds/

# Keybind root or "modifier"
$mainMod = SUPER

# Keybindings for applications
bind = $mainMod, Return, exec, alacritty
bind = $mainMod, E, exec, yazi,
bind = $mainMod, R, exec, wofi --show drun,run
bind = $mainMod, S, exec, grim -g "$(slurp -d)" "$HOME/screenshots/$(date '+%y%m%d_%H-%M-%S').png"
bind = $mainMod, W, exec, sh "$HOME/.hick-os/scripts/pick-a-paper.sh"

# Keybindings for window manipulation
bind = $mainMod, C, togglesplit, # Toggle window split mode (Horizontal/Vertical)
bind = $mainMod, V, togglefloating, # Toggle window float
bind = $mainMod, X, killactive,  # Kill/Destroy window
bind = $mainMod, P, pseudo, # Tile window, but no auto sizing

# (VIM) Keybindings for changing focus window 
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Keybinding for switching workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Keybinding to move an active window to a specific workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Keybindings to move/resize windows
bindm = $mainMod, mouse:272, movewindow # Right mouse button
bindm = $mainMod, mouse:273, resizewindow # Left mouse button
