# My triple monitor setup
#
# NOTE: https://wiki.hyprland.org/Configuring/Monitors/
monitor=HDMI-A-2,preferred,0x0,1,transform,1 # Left Monitor
monitor=DP-2,preferred,1440x560,1 # Center Monitor
monitor=HDMI-A-1,preferred,4000x0,1,transform,3 # Right Monitor

# Drawing Tablet
#
# NOTE: It's ONLY `HDMI-A-2` when my left monitor is NOT in use.
#monitor=HDMI-A-2,1920x1080@60.00000,2560x0,1
