general {
    # Window gaps
    gaps_in = 15
    gaps_out = 20

    # Window border
    border_size = 1
    col.active_border = rgba(11d4adee) rgba(ffffffff) 90deg # Teal top fading into white bottom 
    #col.active_border = rgba(ffffffff) # Solid white 
    col.inactive_border = rgba(595959aa)

    layout = dwindle

    # Enabling screen tearing will reduce latency and/or jitter in games.
    #
    # NOTE: Tearing will only be in effect when the game is in fullscreen and 
    #       the only thing visible on the screen.
    #
    # NOTE: Docs @ https://wiki.hyprland.org/Configuring/Tearing/
    allow_tearing = true
}

dwindle {
    # NOTE: Docs @ https://wiki.hyprland.org/Configuring/Dwindle-Layout/
    pseudotile = yes
    preserve_split = yes
}

master {
    # NOTE: Docs @ https://wiki.hyprland.org/Configuring/Master-Layout/
    new_status = "master"
}

misc {
    force_default_wallpaper = 0 # Gets rid of the damn default anime girl wallpaper
    disable_splash_rendering = true # Gets rid of the damn qoutes forced on mi screen
}
