# Rules to achieve different behaviors for specific windows.
#
# NOTE: Docs @ https://wiki.hypr.land/Configuring/Window-Rules/

# Auto kill annoying ass World of Warcraft error debug popups.
windowrule {
  name = kill-wow-error-popups
  match:title = ^(Fatal Error - WowVoiceProxy\.exe|World of Warcraft Voice Proxy)$

  no_initial_focus = on
  exec = hyprctl dispatch killactive
}
