# Workspace Rules
#
# DOCS: https://wiki.hypr.land/Configuring/Workspace-Rules/

# Workspace 1: General / Home / Misc / Coding.
# Monitor: Center (Default).
workspace = 1, monitor:DP-2, persistent:true, default:true

# Workspace 2: Research & Development.
# Monitor: Center.
workspace = 2, monitor:DP-2, persistent:true

# Workspace 3: Research & Development (Extra).
# Monitor: Center.
workspace = 3, monitor:DP-2, persistent:true

# Workspace 4: Internet browsing & research.
# Monitor: Left (Default).
workspace = 4, monitor:HDMI-A-2, persistent:true, default:true

# Workspace 5: Communications & social.
# Monitor: Right (Default).
workspace = 5, monitor:HDMI-A-1, persistent:true, default:true

# Workspace 6: Gaming & recreation.
# Monitor: Center.
workspace = 6, monitor:DP-2, persistent:true

# Workspace 7: Art & design.
# Monitor: Center.
workspace = 7, monitor:DP-2, persistent:true

# Workspace 8: Meetings & calls.
# Monitor: Left.
workspace = 8, monitor:HDMI-A-2, persistent:true

# Workspace 9: Random & junk.
# Monitor: Center.
workspace = 9, monitor:DP-2, persistent:true
