# Window Rule for Alacritty windows
windowrule {
  name="Alacritty Opacity"
  match:class = ^(Alacritty)$
  # NOTE: Typically don't like opacity bc hard to see text
  # but with a strong blur this level of opacity is fine.
  opacity = 0.90
}
