#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
./.screenlayout/3-monitor.sh &
feh --bg-scale hick-os/wallpapers/spiral-galaxy-portrait.jpg  --bg-scale hick-os/wallpapers/cold-qt-3.14.jpg --bg-scale hick-os/wallpapers/spiral-galaxy-portrait.jpg &

bspc monitor -d I II III IV

bspc config border_width         4
bspc config active_border_color  "#d79921"
bspc config normal_border_color  "#98971a"
bspc config focused_border_color "#cc241d"

bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
